### ISSUE TITLE
Initial Formulation Evaluation

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#103]
Task to track development of initial formulation evaluation components to facilitate various MaaS workflows.

## Subtasks
(Add and/or spin off to separate issues as needed)

- [ ] Create DMOD Evaluation service components
- [ ] Develop or link with Evaluation backend
- [ ] Create appropriate GUI, file output, and internal distribution components for using Evaluation output
