### ISSUE TITLE
Create Nextgen-Canonical Forcing Engine Library Package

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#104]
Develop a forcing engine that can ingest AORC forcing data (and can be extended to include others) and process the data to the canonical format for the Nextgen framework.  

- [ ] Process received raw data to canonical
- [ ] Write canonical data to supported _Dataset_ types
- [ ] Read canonical data from supported _Dataset_ types
- [ ] Provide public interface for accessing canonical data directly

**Comment by robertbartel** [comment]
This may or may not be required, at least for FIHM, depending on the eventual needs and development direction of the Nextgen framework and its own forcing engine implementation (see perhaps [ngen-367](https://github.com/NOAA-OWP/ngen/pull/367) and [ngen-369](https://github.com/NOAA-OWP/ngen/pull/369))

**Comment by robertbartel** [comment]
Marking as a "wishlist" item, specifically for FIHM deliverable, but unlinking from that milestone in particular as it has been determined to not strictly be necessary in that time frame.

**Comment by robertbartel** [comment]
This will be handled in the separate _ngen-forcings_ repo.
