### ISSUE TITLE
Service component for internal dataset handling

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#121]
Implement service component for managing forcing, configuration, and other category dataset handling.   

This may need to be developed from the partially implemented`datarequestservice` package, perhaps with some refactoring/renaming of things.

- [x] #138
- [x] #153
- [x] #139
- [x] Data service support for dataset catalog and querying/search for datasets based on matching _DataDomain_ or sub-domain
- [x] Data service support for checking if required data for a job is available
- [x] Data service support for serving canonical forcing data (directly and/or indirectly; e.g., via object store dataset)
- [x] Data service support for removing existing datasets

**Comment by robertbartel** [comment]
Work for this item is complete, but in the PR queue.  This is reflected in its Github Project status.  Once the `launch_jobs/14_more_data_fixes` branch is merged, the status can be changed from _In Edge_ to _Done_.
