### ISSUE TITLE
Next Release Post-June-2022

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#167]
Ticket to collect issues that are part of the next release (like to be represented by a new Github Project).

- [ ] #162
- [ ] #93 
- [ ] #127
- [ ] Incorporate monitor-service
- [ ] Enhance job startup monitoring to auto restart hung workers that don't start on their own 
- [ ] Model output access view (specialized beyond just generic output dataset management view) 
- [ ] Finish GUI views for model configuration 
  - [ ] Finalize domain selection GUI view
  - [ ] Component for configuring "regular" BMI formulations
  - [ ] Component for configuring multi-BMI formulations
  - [ ] Support the uploading of all required catchment-specific model formulation BMI initialization files
- [ ] Complete client package/CLI support for dataset upload/download functionality
- [ ] Further work on Docker images for ngen workers
  - [ ] Determine how to design image configurations best to add routing support
  - [ ] Ensure routing support is optionally available in ngen-based worker image(s)
  - [ ] Add/improve mechanism(s) for controlling specific ngen repo commit
  - [ ] Design build, backend, and/or UI mechanisms to support ngen workflows using externally provided/referenced BMI module code
  - [ ] Investigate possible support of custom provided Docker image or Dockerfile
- [ ] #64
- [ ] #61
- [ ] #103
- [ ] Data service support for automated routines to clean up temporary datasets
- [ ] Enhance subset-service to work with multiple hydrofabrics obtained via datasets from data-service
- [ ] Ensure support for specifying job allocation paradigm via CLI/GUI/client package
- [ ] Create (i.e., recreate, but with new names) allocation paradigms that are multiple MPI ranks per container
- [ ] Add client package support for requesting a job and designating a subset of the entire hydrofabric
- [ ] Cleanup/merge of `modeldata.datarequest` with `modeldata.data`
- [ ] Catchment grouping constructs for shared configs and catchment aggregations
- [ ] #70
- [ ] Dynamically deactivate/reactivate resources on a Swarm node if the node's status switch to/from “pause”
- [ ] Separate Docker functionality to isolated package
- [ ] Review and update Python package build process and _dist_package.sh_ script
- [ ] Make sure the object-store-dataset-based Docker volume for output datasets that gets created as part of a job is cleaned up upon job completion
- [ ] Review automated testing and improve test coverage
- [ ] Bug Fixes
  - [ ] Debug issues with subset-service startup
  - [ ] #43
  - [ ] #38 
  - [ ] #66 
  - [ ] #67
  - [ ] Fix issues with resource release upon job completion

Optional

- [ ] Data service support for detecting when a derived, regridded forcing dataset has become "stale" due to hydrofabric changes
- [ ] Support deriving (temporary) CSV forcing datasets that are a sub-time-series
- [ ] Support deriving (temporary) CSV forcing datasets that are a subset of catchments 
- [ ] Data service support for search for datasets compatible with a _DataDomain_ that can be used to derive a new dataset for a domain
- [ ] Data service support for deriving datasets to fulfill otherwise unfulfillable requirements for jobs (along with updating data availability check functionality)
- [ ] Investigate large use of Redis and Redis stream for job state management and service queuing
- [ ] Create SUBDIVIDED_HYRDOFABRIC dataset type (or similar) to separate the base HYDROFABRIC data and dataset from subdivisions 
- [ ] Data service support for retrieving data from remote services or locations (possibly with opendap.catalog)
- [ ] Add tool for tracking and managing DMOD-specific node labeling for Docker Swarm service deployment constraints
- [ ] Implement SSL for object store
- [ ] Port stack control scripts to Python
- [ ] Port object store user access init script to Python
