### ISSUE TITLE
Refactoring serialization and deserialization types

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#254]
Meta-issue for tracking progress porting `dmod` libraries to `pydantic`.

- [x] Refactor `dmod.core` ~#239~ (resubmitted #256)
- [x] Refactor `dmod.communication` #253
- [x] Refactor `dmod.scheduler` #270
- [x] Refactor `dmod.modeldata` #257
- [x] Merge updates to `master` into feature branch
- [x] #279

**Comment by aaraney** [comment]
#253 and #257 are ready for review. `dmod.scheduler` refactor is in progress.

**Comment by aaraney** [comment]
#270 is done and ready for review.

**Comment by robertbartel** [comment]
With the completion of #331, we can call this done.
