### ISSUE TITLE
Separate Stand-Alone Request/Gateway Stack and Service(s)

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#414]
- [ ] Create and apply third Docker network for communication with/among _main_ stack services, but separate from MPI worker network
- [ ] Create _gateway_ Docker stack to and move _requestservice_ here
- [ ] Implement Django-backed service within _gateway_ stack (request routing, static resources, API support, etc.)
- [ ] Implement _dataservice_-specific "gateway" service within _gateway_ stack
- [ ] Identify and document other related future tasks (e.g., authentication integration)
