### ISSUE TITLE
Abstract Docker away from DMOD and make it an optional dependency

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/DMOD#703]
# Problem

The US government focuses on using operating systems that do not support docker, meaning that DMOD is wholly incompatible with NOAA architecture. 

# Solution

Create an abstraction layer between the code that _currently_ invokes docker commands and the code that implements it. The current mode of operation should still be supported and the status quo will remain.

Once that is done, an implementation targeting Kubernetes may be developed. Once a version that uses kubernetes rather than docker swarm is completed, DMOD may be able to be run and debugged on NOAA architecture.

## Steps

- [ ] Identify locations where docker is invoked by DMOD
- [ ] Write base classes and protocols that may act as a facade between DMOD and Docker
- [ ] Write the concrete implementation of the base classes that will allow DMOD to orchestrate via Docker
- [ ] Develop the means to configure what abstraction is used for orchestration
- [ ] Write factories that will generate the correct orchestration backend
- [ ] Replace direct calls to docker with direct calls to objects generated by the orchestration backend factories

**Comment by robertbartel** [comment]
@christophertubbs, a good conversation was had in #556 that will relate to this work.

**Comment by christophertubbs** [comment]
@robertbartel , thanks for including the reference to the previous conversation. #556 turned out to be more of a discussion than a call to action, which is what this issue constitutes.

closes #556
